dependencies:
  - smartcontractkit/chainlink-brownie-contracts@0.5.1
  - OpenZeppelin/openzeppelin-contracts@4.8.0

dotenv: .env

compiler:
  solc:
    remappings:
      - "@chainlink=smartcontractkit/chainlink-brownie-contracts@0.5.1"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.8.0"

networks:
  goerli:
    vrf_coordinator: "0x2ca8e0c643bde4c2e08ab1fa0da3401adad7734d"
    eth_usd_price_feed: "0xD4a33860578De61DBAbDc8BFdb98FD742fA7028e"
    link_token: "0x326C977E6efc84E512bB9C30f76E30c160eD06FB"
    wrapperAddress: "0x708701a1DfF4f478de54383E49a627eD4852C816"
    verify: True
  mainnet-fork:
    eth_usd_price_feed: "0x5f4eC3Df9cbd43714FE2740f5E3616155c5b8419"

wallets:
  from_key: ${PRIVATE_KEY}
